networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - angular
      - adminka
      - spring
    networks:
      - default

  angular: 
    build:
      context: ./angular
    networks:
      - default

  adminka:  
    build:
      context: ./adminka
    networks:
      - default

  spring:  
    build:
      context: ./spring/ConstructorApp
    networks:
      - default
